#!/usr/bin/env python3
"""Check if pgvector is available in the Neon database."""

import urllib.request
import json

print("=" * 60)
print("STEP 2: DATABASE SETUP - pgvector")
print("=" * 60)
print()
print("STEP 2A: Check Neon pgvector support")
print("-" * 40)
print()
print("Neon has different pgvector support by tier:")
print("  - Neon Free:  pgvector IS available (via vec) but LIMITED")
print("  - Neon Paid:  pgvector FULLY supported with HNSW")
print()
print("To check your database NOW:")
print()
print("  Option 1: Via Neon Console (https://neon.tech)")
print("    1. Open your project")
print("    2. Go to SQL Editor")
print("    3. Run these commands:")
print()
print("      -- Enable pgvector extension")
print("      CREATE EXTENSION IF NOT EXISTS vector;")
print()
print("      -- Verify extension is installed")
print("      SELECT extname FROM pg_extension WHERE extname = 'vector';")
print()
print("      -- If you see 'vector' in result -> pgvector is available!")
print()
print("  Option 2: Via psql (local terminal)")
print("    psql $DATABASE_URL")
print("    CREATE EXTENSION IF NOT EXISTS vector;")
print("    SELECT extname FROM pg_extension WHERE extname = 'vector';")
print()
print("=" * 60)
print("STEP 2B: Prisma Commands")
print("-" * 40)
print()
print("After verifying pgvector, run these from project root:")
print()
print("  1. Generate Prisma client:")
print("     npx prisma generate")
print()
print("  2. Push schema to database (this updates your DB):")
print("     npx prisma db push")
print()
print("  3. Verify the embedding column was created:")
print("     npx prisma studio  (opens GUI to view tables)")
print()
print("=" * 60)
print("STEP 2C: Troubleshooting")
print("-" * 40)
print()
print("ERROR: extension 'vector' is not available")
print("  -> Neon Free tier may have limited vector support")
print("  -> Solution: Use Qdrant (external vector DB) instead")
print("     See services/ml-service/README.md for Qdrant setup")
print()
print("ERROR: permission denied for extension vector")
print("  -> Check your Neon connection string in .env")
print("  -> Make sure you're using the correct DATABASE_URL")
print()
print("SUCCESS indicators:")
print("  - 'vector' appears in pg_extension query result")
print("  - npx prisma db push completes without error")
print("  - Product table in Prisma Studio shows embedding column")
print()
print("=" * 60)
